---
  - name: "First example"
    hosts: 192.168.0.66
    tasks:

    - name: "just execute a ls -lrt command"
      shell: "ls -la ~/ "
      register: "output"
    - debug: var=output.stdout_lines
